dist: trusty
language: node_js
before_install:
  - git submodule update --init --recursive
node_js:
  - "8"
  - "10.15.1"
  - "12"
os:
  - osx
  # - linux
  # - windows
script: npm run-script travis

