dist: trusty
language: node_js
before_install:
  - git submodule update --init --recursive
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
os:
  - osx
  - linux

matrix:
  include:
    - os: windows
      node_js: "8"
    - os: windows
      node_js: "10"
    - os: windows
      node_js: "12"
    - os: windows
      node_js: "13"
  allow_failures:
    - os: windows
      node_js: "8"
    - os: windows
      node_js: "10"
    - os: windows
      node_js: "12"
    - os: windows
      node_js: "13"
  fast_finish: true


script: npm run-script travis

